server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: dev
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=Truth, hello world!
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
      default-filters:
        - AddRequestHeader=Truth, hello world! #所有服务均生效的过滤器
      globalcors:
        add-to-simple-url-handler-mapping: true #解决options请求被拦截的问题
        cors-configurations:
          '[/**]':
            allowedOrigins: #允许哪些网站跨域请求
              - "http://localhost:8090"
            allowedMethods: #允许跨域的ajax请求
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*" #允许在请求中携带的头信息
            allowedCredentials: true #是否允许携带cookie
            maxAge: 36000 #跨域检测有效期
